<a href="https://colab.research.google.com/github/vineethavijayn/vineethavijayn/blob/main/NaiveB_PlayTennis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd

outlook=['sunny','sunny','overcast','rainy','rainy','rainy',
         'overcast','sunny','sunny','rainy','sunny',
         'overcast','overcast','rainy']
temperature=['hot','hot','hot','mild','cool','cool','cool','mild',
             'cool','mild','mild','mild','hot','mild']
humidity=['high','high','high','high','normal','normal',
          'normal','high','normal','normal','normal','high','normal','high']

wind=['weak','strong','weak','weak','weak','strong','strong','weak',
      'weak','weak','strong','strong','weak','strong']

play=['no','no','yes','yes','yes','no','yes','no','yes','yes',
      'yes','yes','yes','no']

In [10]:
##Encoding
#1. Label Encoder

from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

outlook_encoder=label.fit_transform(outlook)
outlook_encoder


array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [11]:
temp_encoder=label.fit_transform(temperature)
temp_encoder

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [13]:
humidity_encoder=label.fit_transform(humidity)
humidity_encoder

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [15]:
wind_encoder=label.fit_transform(wind)
wind_encoder

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [16]:
features=list(zip(outlook_encoder,temp_encoder,humidity_encoder,wind_encoder))
features

[(2, 1, 0, 1),
 (2, 1, 0, 0),
 (0, 1, 0, 1),
 (1, 2, 0, 1),
 (1, 0, 1, 1),
 (1, 0, 1, 0),
 (0, 0, 1, 0),
 (2, 2, 0, 1),
 (2, 0, 1, 1),
 (1, 2, 1, 1),
 (2, 2, 1, 0),
 (0, 2, 0, 0),
 (0, 1, 1, 1),
 (1, 2, 0, 0)]

In [ ]:
#--------------------Naive Bayes-----------3 types of classifiers
# 1. Gaussian      ---- is used if the data is continous data
# 2. Multinomial.  ---- if the data is discrete data (discrete ---> the data after encoding)
# 3. Bernouli.     ---- combination of Gaussian and multinomial

In [17]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(features,play)

MultinomialNB()

In [18]:
print(model.predict([[2,0,0,1]]))

['no']
