<a href="https://colab.research.google.com/github/vineethavijayn/vineethavijayn/blob/main/winequality_knn_luminar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Luminar_Projects/luminar_dataset/winequality-red (1).csv',sep=',')
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [2]:
df.isna().sum()

fixed acidity           0
volatile acidity        2
citric acid             0
residual sugar          3
chlorides               0
free sulfur dioxide     3
total sulfur dioxide    0
density                 9
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [26]:
# x=df[0].median()
# df[0].fillna(x,inplace=True)

x=df['volatile acidity'].mean()
df['volatile acidity'].fillna(x,inplace=True)

In [9]:
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          3
chlorides               0
free sulfur dioxide     3
total sulfur dioxide    0
density                 9
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [10]:
y=df['residual sugar'].mean()
df['residual sugar'].fillna(y,inplace=True)


In [11]:
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     3
total sulfur dioxide    0
density                 9
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [12]:
z=df['free sulfur dioxide'].mean()
df['free sulfur dioxide'].fillna(z,inplace=True)

In [13]:
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 9
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [14]:
a=df['density'].mean()
df['density'].fillna(a,inplace=True)

In [15]:
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [27]:
x=df.iloc[:,:-1].values
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [28]:
y=df.iloc[:,-1].values
y

array([5, 5, 5, ..., 6, 5, 6])

In [77]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)

In [22]:
y_train

array([7, 5, 5, ..., 5, 7, 6])

In [78]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=23)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([6, 5, 6, 6, 6, 5, 6, 6, 5, 5, 5, 6, 5, 5, 6, 6, 7, 5, 6, 5, 6, 6,
       6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 6, 5, 6, 6, 6, 6, 7, 5, 6,
       5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 5, 5, 5, 7, 5, 5, 6, 6, 5, 5, 6,
       5, 6, 5, 7, 5, 5, 5, 5, 6, 6, 5, 5, 5, 6, 6, 5, 5, 6, 6, 6, 5, 5,
       5, 5, 5, 5, 5, 6, 7, 5, 6, 6, 5, 6, 7, 6, 6, 6, 5, 5, 5, 6, 6, 5,
       6, 5, 6, 5, 5, 6, 5, 7, 6, 6, 5, 6, 6, 5, 5, 6, 5, 5, 5, 6, 5, 5,
       6, 6, 6, 5, 6, 5, 6, 6, 6, 5, 5, 5, 5, 6, 6, 7, 6, 6, 5, 5, 6, 5,
       5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 5, 5, 5, 7, 5, 6,
       7, 7, 5, 5, 5, 6, 6, 6, 6, 5, 6, 6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5,
       6, 5, 5, 6, 5, 5, 5, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5, 6, 6, 5, 5, 5,
       5, 6, 6, 6, 5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 6, 6, 6, 5, 6, 6, 5, 6,
       6, 6, 6, 5, 6, 5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 5, 5, 6, 6, 6, 5,
       5, 5, 6, 5, 6, 5, 5, 5, 6, 5, 6, 6, 6, 5, 6, 6, 6, 6, 5, 6, 5, 5,
       6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 5, 5, 6,

In [79]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[  0,   0,   0,   3,   0,   0],
       [  0,   0,  12,   2,   1,   0],
       [  0,   0, 141,  65,   2,   0],
       [  0,   0,  79, 118,   7,   0],
       [  0,   0,  13,  25,   7,   0],
       [  0,   0,   1,   2,   2,   0]])

In [80]:
score=accuracy_score(y_test,y_pred)
score

0.5541666666666667